#!/usr/bin/expect -f

spawn telnet 192.168.1.111
#username： root
#password： (enter)

expect {
    "login" {
        send "root\r";
        exp_continue
    }
    "*Password:" {
        send "\n\r"
    }
}

send "cfg get software_version\r"
send "cat /etc/svn-up.log\n"

interact #执行完成后保持交互状态，把控制权交给控制台
