#!/bin/bash

PWD=`pwd`
user=$USER
home=$HOME
hostname=`hostname`

HOST1NAME="vanxum02"


# 终端输入提示
if [ x$hostname != x$HOST1NAME ]; then
	PS1="\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\n=====>\[\e[31m\]\$\[\e[0m\]"
	#PS1="\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\[\e[31m\]\$\[\e[0m\]"
else
	PS1="\A [\u]@[\h]\w\n=====>\$"
fi


#习惯的使用别名
alias vi='vim'
alias grep='grep --color'
alias man='viman'

if [ hash colordiff 2> /dev/null ]; then
	echo "I require colordiff but it's not installed.  Aborting."
else
	alias diff='colordiff'
fi

alias ebuild='ssh -X shaowangquan@172.16.200.101'
alias mbuild='sudo sshfs  shaowangquan@172.16.200.101:/home/shaowangquan /home/wqshao/build-dir -o gid=1000,uid=1000,allow_other'


# for tmux
export TERM="screen-256color"


# "CTRL-S：挂起终端（XON） "CTRL-Q：恢复终端（XOFF） "要禁止这些键盘映射
stty -ixon


# locale环境
export LC_ALL=C

echo "	Winddoing"


