#!/bin/bash

PWD=`pwd`
user=$USER
home=$HOME
hostname=`hostname`

HOST1NAME1="vanxum02"
HOST1NAME2="ubuntu"

function git_branch {
    branch="`git branch 2>/dev/null | grep "^\*" | sed -e "s/^\*\ //"`"
    if [ "${branch}" != "" ];then
        if [ "${branch}" = "(no branch)" ];then
            branch="(`git rev-parse --short HEAD`...)"
        fi
        echo "($branch)"
    fi
}

function ssh_info {
    local ssh_info="`echo $SSH_CONNECTION | awk '{print $3}'`"
    if [ -n "$ssh_info" ];then
        echo " in $ssh_info "
    fi
}

function x() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# tmux
function tmux_new()
{
	local session=$1
	echo "tmux new $session session"
	tmux ls | grep "$session"
	if [ $? -ne 0 ]; then
		(tmux new -s $session -d) #后台运行
	else
		echo -e "\t$session session was created ..."
	fi
	echo "tmux new OK"
}

function tmux_startup()
{
	echo "mux_startup TMUX=$TMUX"
	if which tmux 2>&1 >/dev/null; then
		tmux_new "init_session"
		tmux_new "other_session"

		#每次连接都进入init_session会话
		test -z "$TMUX" && (tmux attach -t init_session)
	fi
}

function md5str()
{
    echo "Calculate simple string: [$1]"; echo -n "MD5: "; echo -n "$1" | md5sum;
}


# 终端输入提示
if [ x$hostname = x$HOST1NAME1 ]; then
    PS1='\A [\u@\h]\w\n↪$(ssh_info)=>$(git_branch)\$'
    export LESSCHARSET=utf-8 #git log中文乱码
    tmux_startup
elif [ x$hostname = x$HOST1NAME2 ]; then
    PS1='\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\n↪$(ssh_info)=>\[\033[01;36m\]$(git_branch)\[\e[0m\]\[\e[31m\]\$\[\e[0m\]'
    tmux_startup
else
    #PS1='\u@\h \[\033[01;36m\]\W\[\033[01;32m\]$(git_branch)\[\033[00m\]\$ '
    PS1='\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\n↪$(ssh_info)=>\[\033[01;36m\]$(git_branch)\[\e[0m\]\[\e[31m\]\$\[\e[0m\]'
    #PS1="\[\e[36m\]\A \[\e[32m\][\u\[\e[31m\]@\[\e[33m\]\h\[\e[32m\]]\w\[\e[31m\]\$\[\e[0m\]"
    if [ -n "$SSH_CONNECTION" ]; then
        tmux_startup
    fi
fi


#习惯的使用别名
alias vi='vim'
alias grep='grep --color'
alias man='viman'
alias astyle-c='astyle --style=linux --indent=force-tab=4 --convert-tabs --pad-oper --unpad-paren --break-blocks=all'  #缩进4个空格

if [ hash colordiff 2> /dev/null ]; then
    echo "I require colordiff but it's not installed.  Aborting."
else
    alias diff='colordiff'
fi

alias ebuild='ssh -X shaowangquan@172.16.200.101'
alias m-build='sudo sshfs  shaowangquan@172.16.200.101:/home/shaowangquan /home/wqshao/build-dir -o gid=1000,uid=1000,allow_other'
#alias m-share='sudo mount -t cifs -o username=xxx,domain=xxx,password=xxx,iocharset=utf8,dir_mode=0755,file_mode=0666,uid=wqshao,gid=wqshao //192.186.1.1/home /home/wqshao/share; ls /home/wqshao/share'
alias ydict='ydict'
alias dia="env GTK_IM_MODULE=xim dia"
alias matlab='$HOME/software/matlab/bin/matlab'
# https://motrix.app && chmod +x Motrix-1.1.3-x86_64.AppImage
alias motrix='$HOME/software/Motrix-1.1.3-x86_64.AppImage'
alias listen1='$HOME/software/Listen1_2.4.0_linux_x86_64.AppImage'
alias drawio='$HOME/software/draw.io-x86_64-11.1.4.AppImage'
alias enca-utf-8='enca -L zh_CN -x UTF-8'

# Git Repo 镜像, https://mirrors.tuna.tsinghua.edu.cn/help/git-repo/
export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo/'

# for android build, 为了去除所有本地化的设置，让命令能正确执行
#export LC_ALL=C

# for tmux
export TERM="screen-256color"

# "CTRL-S：挂起终端（XON） "CTRL-Q：恢复终端（XOFF） "要禁止这些键盘映射
stty -ixon

# window10 for ubuntu

uname -a | grep "Microsoft"  >> /dev/null
if [ $? -eq 0 ]; then
    alias wqshao='cd /mnt/f/wqshao'
    echo wqshao | sudo -S service ssh restart && echo "Restart SSH" >> /dev/null
    tmux_startup
fi

echo "Winddoing"
screenfetch

